name: Build and test of Java Project

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
          cache: maven  # Cache dependencies to speed up the build process

      # Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Add a verification step to check if dependencies are properly resolved
      - name: Verify dependencies
        run: mvn dependency:tree

      # Optionally, upload the .jar file as an artifact
      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: Small3DRenderer
          path: target/*.jar

      # Optional: Update Maven dependency graph for Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
