name: Java CI with Maven and Launch4j

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 1: Install Launch4j on Ubuntu
    - name: Install Launch4j
      run: |
        sudo apt-get update
        sudo apt-get install -y launch4j

    # Step 2: Use Launch4j to create the .exe file
    - name: Generate .exe with Launch4j
      run: |
        launch4j --config launch4j-config.xml

    # Step 3: Upload the .exe as an artifact (optional)
    - name: Upload .exe file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-exe
        path: path/to/generated/exe/my-app.exe  # Adjust with the path to the .exe file

    # Optional: Step 4: Create a GitHub release and upload .exe (for easy sharing)
    - name: Create GitHub release and upload .exe
      uses: softprops/action-gh-release@v1
      with:
        files: path/to/generated/exe/my-app.exe  # Adjust with the path to the .exe file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
