name: Java CI with jpackage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows for .exe generation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Create a shorter working directory
      run: mkdir C:\build

    - name: Copy repository to shorter directory
      run: xcopy /E /I . C:\build\Small3DRenderer

    - name: Build with Maven
      working-directory: C:\build\Small3DRenderer
      run: mvn -B package --file pom.xml

    - name: List target directory (for debugging)
      working-directory: C:\build\Small3DRenderer
      run: dir target

    - name: Ensure output directory exists
      run: mkdir C:\output

    - name: Create standalone .exe installer with jpackage
      working-directory: C:\build\Small3DRenderer
      run: |
        jpackage ^
          --name Small3DRenderer ^
          --input target ^
          --main-jar Small3DRenderer-1.0-SNAPSHOT.jar ^
          --main-class org.example.Main ^
          --type exe ^
          --dest C:\output ^
          --win-menu ^
          --win-shortcut ^
          --win-dir-chooser ^
          --win-per-user-install ^
          --win-upgrade-uuid "123e4567-e89b-12d3-a456-426614174000"

    - name: List output directory (for debugging)
      run: dir C:\output

    - name: Upload standalone installer as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer-Installer
        path: C:\output\*.exe
