name: Java CI with Launch4J

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows for .exe generation

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Create a shorter working directory
      run: mkdir C:\build

    - name: Copy repository to shorter directory
      run: xcopy /E /I . C:\build\Small3DRenderer

    - name: Build with Maven
      working-directory: C:\build\Small3DRenderer
      run: mvn -B package --file pom.xml

    - name: List target directory (for debugging)
      working-directory: C:\build\Small3DRenderer
      run: dir target

    - name: Ensure output directory exists
      run: mkdir C:\output

    # Download Launch4J (version 3.50) using wget
    - name: Download Launch4J
      run: |
        wget https://github.com/launch4j/launch4j/releases/download/3.50/launch4j-3.50-win64.zip -O C:\launch4j.zip
        # Unzip the downloaded file
        powershell -Command "Expand-Archive -Path C:\launch4j.zip -DestinationPath C:\launch4j"
        # Clean up the zip file after extracting
        Remove-Item -Path C:\launch4j.zip

    # Verify Launch4J directory (for debugging)
    - name: Verify Launch4J installation
      run: dir C:\launch4j

    # Create Launch4J configuration file
    - name: Create Launch4J configuration file
      run: |
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > C:\build\Small3DRenderer\launch4j-config.xml
        echo "<launch4jConfig>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <dontWrapJar>false</dontWrapJar>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <headerType>gui</headerType>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <jar>C:/output/Small3DRenderer/app/Small3DRenderer-1.0-SNAPSHOT.jar</jar>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <outfile>C:/output/Small3DRenderer.exe</outfile>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <errTitle>You have to download the latest Java Version</errTitle>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <cmdLine></cmdLine>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <chdir>.</chdir>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <priority>normal</priority>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <downloadUrl>https://www.oracle.com/java/technologies/javase/jdk23-archive-downloads.html</downloadUrl>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <supportUrl>https://github.com/moisitx/Small3DRenderer/blob/master/README.md</supportUrl>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <stayAlive>false</stayAlive>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <restartOnCrash>true</restartOnCrash>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <icon>C:/output/Small3DRenderer/app/Screenshot_1.ico</icon>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <classPath>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <mainClass>org.example.Main</mainClass>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  </classPath>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <jre>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <path>C:/output/Small3DRenderer/runtime</path>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <requiresJdk>true</requiresJdk>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <requires64Bit>false</requires64Bit>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <minVersion>23.0.1</minVersion>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <maxVersion></maxVersion>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  </jre>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  <versionInfo>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <fileVersion>1.0.0.0</fileVersion>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <txtFileVersion>1.0 (Initial Release)</txtFileVersion>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <fileDescription>3D Shape Renderer and Visualizer</fileDescription>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <copyright>Copyright (c) 2025 Moises Fernandez Fernandez</copyright>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <productVersion>1.0.0.0</productVersion>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <txtProductVersion>1.0 (Initial Release)</txtProductVersion>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <productName>Small 3D Renderer</productName>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <internalName>Small3DRenderer</internalName>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <originalFilename>Small3DRenderer.exe</originalFilename>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "    <language>ENGLISH_US</language>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "  </versionInfo>" >> C:\build\Small3DRenderer\launch4j-config.xml
        echo "</launch4jConfig>" >> C:\build\Small3DRenderer\launch4j-config.xml

    # Run Launch4J to create the .exe
    - name: Run Launch4J to create the .exe
      run: |
        C:\launch4j\bin\launch4j C:\build\Small3DRenderer\launch4j-config.xml

    - name: List output directory (for debugging)
      run: dir C:\output

    - name: Upload full application package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer-App
        path: C:\output\Small3DRenderer.exe
