name: Java CI with Maven and Launch4J

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Download Launch4J 3.50
      run: |
        wget https://downloads.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz
        tar -xzf launch4j-3.50-linux-x64.tgz
        chmod +x launch4j/launch4j  # Make the executable file executable

    - name: Configure Launch4J
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <launch4jConfig>
          <dontWrapJar>false</dontWrapJar>
          <headerType>gui</headerType>
          <jar>target/Small3DRenderer.jar</jar>
          <outfile>target/Small3DRenderer.exe</outfile>
          <errTitle>You have to download the latest Java Version</errTitle>
          <cmdLine></cmdLine>
          <chdir>.</chdir>
          <priority>normal</priority>
          <downloadUrl>https://www.oracle.com/java/technologies/javase/jdk23-archive-downloads.html</downloadUrl>
          <supportUrl>https://github.com/moisitx/Small3DRenderer/blob/master/README.md</supportUrl>
          <stayAlive>false</stayAlive>
          <restartOnCrash>true</restartOnCrash>
          <manifest></manifest>
          <icon></icon>
          <classPath>
            <mainClass>org.example.Main</mainClass>
          </classPath>
          <jre>
            <path>%JAVA_HOME%;%PATH%</path>
            <requiresJdk>true</requiresJdk>
            <requires64Bit>false</requires64Bit>
            <minVersion>23.0.1</minVersion>
            <maxVersion></maxVersion>
          </jre>
          <versionInfo>
            <fileVersion>1.0.0.0</fileVersion>
            <txtFileVersion>1.0 (Initial Release)</txtFileVersion>
            <fileDescription>3D Shape Renderer and Visualizer</fileDescription>
            <copyright>Copyright (c) 2025 Moises Fernandez Fernandez</copyright>
            <productVersion>1.0.0.0</productVersion>
            <txtProductVersion>1.0 (Initial Release)</txtProductVersion>
            <productName>Small 3D Renderer</productName>
            <companyName></companyName>
            <internalName>Small3DRenderer</internalName>
            <originalFilename>Small3DRenderer.exe</originalFilename>
            <trademarks></trademarks>
            <language>ENGLISH_US</language>
          </versionInfo>
        </launch4jConfig>' > launch4j.xml

    - name: Run Launch4J
      run: |
        ./launch4j/launch4j launch4j.xml

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer
        path: target/Small3DRenderer.exe
