name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List target directory (for debugging)
      run: ls -l target/

    - name: Convert .jar to .exe using jpackage
      run: |
        # Ensure the .jar file exists
        JAR_FILE=$(ls target/*.jar)
        if [ -z "$JAR_FILE" ]; then
          echo "No .jar file found in target directory!"
          exit 1
        fi

        # Create a directory for the .exe output
        mkdir -p dist

        # Use jpackage to create a .exe
        jpackage \
          --type app-image \
          --input target \
          --main-jar $(basename $JAR_FILE) \
          --main-class com.example.Main \  # Replace with your main class
          --name Small3DRenderer \
          --dest dist

        # Package the app-image into a .exe
        jpackage \
          --type exe \
          --app-image dist/Small3DRenderer \
          --name Small3DRenderer \
          --dest dist

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer
        path: dist/Small3DRenderer.exe
