name: Java CI with Multi-Platform Support

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest  # Use Windows for .exe generation

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List target directory (for debugging)
      run: dir target

    - name: Download Launch4J 3.50
      run: |
        curl -L -o launch4j.zip https://downloads.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-win32.zip

    - name: Extract Launch4J
      run: |
        Expand-Archive -Path launch4j.zip -DestinationPath launch4j

    - name: Configure Launch4J
      run: |
        $launch4jConfig = @"
        <?xml version="1.0" encoding="UTF-8"?>
        <launch4jConfig>
          <dontWrapJar>false</dontWrapJar>
          <headerType>gui</headerType>
          <jar>target\Small3DRenderer-1.0-SNAPSHOT.jar</jar>
          <outfile>C:\output\Small3DRenderer.exe</outfile>
          <errTitle>You have to download the latest Java Version</errTitle>
          <cmdLine></cmdLine>
          <chdir>.</chdir>
          <priority>normal</priority>
          <downloadUrl>https://www.oracle.com/java/technologies/javase/jdk23-archive-downloads.html</downloadUrl>
          <supportUrl>https://github.com/moisitx/Small3DRenderer/blob/master/README.md</supportUrl>
          <stayAlive>false</stayAlive>
          <restartOnCrash>true</restartOnCrash>
          <manifest></manifest>
          <icon>C:\output\Screenshot_1.ico</icon>
          <classPath>
            <mainClass>org.example.Main</mainClass>
          </classPath>
          <jre>
            <path>%JAVA_HOME%</path>
            <requiresJdk>true</requiresJdk>
            <requires64Bit>false</requires64Bit>
            <minVersion>23.0.1</minVersion>
            <maxVersion></maxVersion>
          </jre>
          <versionInfo>
            <fileVersion>1.0.0.0</fileVersion>
            <txtFileVersion>1.0 (Initial Release)</txtFileVersion>
            <fileDescription>3D Shape Renderer and Visualizer</fileDescription>
            <copyright>Copyright (c) 2025 Moises Fernandez Fernandez</copyright>
            <productVersion>1.0.0.0</productVersion>
            <txtProductVersion>1.0 (Initial Release)</txtProductVersion>
            <productName>Small 3D Renderer</productName>
            <companyName></companyName>
            <internalName>Small3DRenderer</internalName>
            <originalFilename>Small3DRenderer.exe</originalFilename>
            <trademarks></trademarks>
            <language>ENGLISH_US</language>
          </versionInfo>
        </launch4jConfig>
        "@
        Set-Content -Path launch4j-config.xml -Value $launch4jConfig

    - name: Run Launch4J to create standalone .exe
      run: |
        .\launch4j\launch4j.exe launch4j-config.xml

    - name: Upload standalone .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer-Windows
        path: C:\output\Small3DRenderer.exe

  build-linux:
    runs-on: ubuntu-latest  # Use Ubuntu for Linux package generation

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List target directory (for debugging)
      run: ls -l target

    - name: Create Linux package with jpackage
      run: |
        mkdir -p output
        jpackage --name Small3DRenderer --input target --main-jar Small3DRenderer-1.0-SNAPSHOT.jar --main-class org.example.Main --type app-image --dest output

    - name: Package the application image into a tarball
      run: |
        cd output
        tar -czf Small3DRenderer-linux.tar.gz Small3DRenderer

    - name: Upload Linux package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer-Linux
        path: output/Small3DRenderer-linux.tar.gz
