name: Java CI with Launch4J

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows for .exe generation

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Create a shorter working directory
      run: mkdir C:\build

    - name: Copy repository to shorter directory
      run: xcopy /E /I . C:\build\Small3DRenderer

    - name: Build with Maven
      working-directory: C:\build\Small3DRenderer
      run: mvn -B package --file pom.xml

    - name: List target directory (for debugging)
      working-directory: C:\build\Small3DRenderer
      run: dir target

    - name: Download Launch4J
      run: |
        curl -L -o launch4j-3.50-win32.zip "https://downloads.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-win32.zip"
        Expand-Archive -Path launch4j-3.50-win32.zip -DestinationPath . 

    - name: List Launch4J directory (for debugging)
      run: dir launch4j

    - name: Configure Launch4J
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <launch4jConfig>
          <dontWrapJar>false</dontWrapJar>
          <headerType>gui</headerType>
          <jar>C:\output\Small3DRenderer\app\Small3DRenderer-1.0-SNAPSHOT.jar</jar>
          <outfile>C:\output\Small3DRenderer.exe</outfile>
          <errTitle>You have to download the latest Java Version</errTitle>
          <cmdLine></cmdLine>
          <chdir>.</chdir>
          <priority>normal</priority>
          <downloadUrl>https://www.oracle.com/java/technologies/javase/jdk23-archive-downloads.html</downloadUrl>
          <supportUrl>https://github.com/moisitx/Small3DRenderer/blob/master/README.md</supportUrl>
          <stayAlive>false</stayAlive>
          <restartOnCrash>true</restartOnCrash>
          <manifest></manifest>
          <icon>C:\output\Small3DRenderer\app\Screenshot_1.ico</icon>
          <classPath>
            <mainClass>org.example.Main</mainClass>
          </classPath>
          <jre>
            <path>C:\output\Small3DRenderer\runtime</path>
            <requiresJdk>true</requiresJdk>
            <requires64Bit>false</requires64Bit>
            <minVersion>23.0.1</minVersion>
            <maxVersion></maxVersion>
          </jre>
          <versionInfo>
            <fileVersion>1.0.0.0</fileVersion>
            <txtFileVersion>1.0 (Initial Release)</txtFileVersion>
            <fileDescription>3D Shape Renderer and Visualizer</fileDescription>
            <copyright>Copyright (c) 2025 Moises Fernandez Fernandez</copyright>
            <productVersion>1.0.0.0</productVersion>
            <txtProductVersion>1.0 (Initial Release)</txtProductVersion>
            <productName>Small 3D Renderer</productName>
            <companyName></companyName>
            <internalName>Small3DRenderer</internalName>
            <originalFilename>Small3DRenderer.exe</originalFilename>
            <trademarks></trademarks>
            <language>ENGLISH_US</language>
          </versionInfo>
        </launch4jConfig>' > launch4j.xml

    - name: Ensure output directory exists
      run: |
        if (-Not (Test-Path -Path C:\output)) {
          New-Item -ItemType Directory -Force -Path C:\output
        }
        if (-Not (Test-Path -Path C:\output\Small3DRenderer)) {
          New-Item -ItemType Directory -Force -Path C:\output\Small3DRenderer
        }

    - name: Run Launch4J
      run: |
        .\launch4j\launch4j.exe launch4j.xml

    - name: List output directory (for debugging)
      run: |
        dir C:\output
        dir C:\output\Small3DRenderer

    - name: Upload full application package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer-App
        path: C:\output\Small3DRenderer\
