name: Java CI with jpackage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest  # Use Windows for .exe generation

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create .exe with jpackage
      run: |
        jpackage --name Small3DRenderer --input target --main-jar Small3DRenderer.jar --main-class org.example.Main --type app-image --dest target/dist

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Small3DRenderer
        path: target/dist/Small3DRenderer.exe
